### ISSUE TITLE
Type declarations

### ISSUE THREAD

**Issue by Kevinrp22** [sekizlipenguen/react-native-popup-confirm-toast#27]
I am trying to use some attributes of the **`Popup`** method (ex. 'type', 'callback'... etc) and although they work, they give me typing errors in vscode, I have looked in the expected types and they are not declared.

![image](https://github.com/user-attachments/assets/2c263c99-ccb0-4e5c-bcee-776792fd5f99)
![image](https://github.com/user-attachments/assets/61a6bfa8-d67d-4383-a12a-58318f9e0fca)

Is it possible that the types in this file are missing? I don't know if more attributes are missing in other methods

![image](https://github.com/user-attachments/assets/805a88bc-7c2b-41dc-a250-b51234bf17cc)

**Comment by sekizlipenguen** [comment]
Thank you for raising this! Could you please try updating your index.d.ts file with the following changes and see if it resolves the issue? I'll release an update based on this if it works for you:

```
declare module "react-native-popup-confirm-toast" {
    import {FC} from "react"
    import {StyleProp, TextStyle, ViewStyle} from "react-native"

    export interface Config {
        title?: string
        text?: string
        titleTextStyle?: StyleProp<TextStyle>
        descTextStyle?: StyleProp<TextStyle>
        backgroundColor?: string
        timeColor?: string
        position?: "top" | "bottom"
        icon?: FC
        timing?: number
        statusBarType?: "default" | "dark-content" | "light-content"
        statusBarTranslucent?: boolean
        statusBarHidden?: boolean
        statusBarAndroidHidden?: boolean
        statusBarAppleHidden?: boolean
        hiddenDuration?: number
        startDuration?: number
        onOpen?: () => void
        onOpenComplete?: () => void
        onClose?: () => void
        onCloseComplete?: () => void
        type?: string;
        callback?: () => void;
    }

    export interface SheetConfig {
        background?: string
        height?: number
        duration?: number
        closeDuration?: number
        closeOnDragDown?: boolean
        closeOnPressMask?: boolean
        closeOnPressBack?: boolean
        dragTopOnly?: boolean
        component?: FC
        onOpen?: () => void
        onOpenComplete?: () => void
        onClose?: () => void
        onCloseComplete?: () => void
        customStyles?: StyleProp<ViewStyle>
        timing?: number
        keyboardHeightAdjustment?: boolean
    }

    export interface Toast {
        show: (props: Config) => void
        hide: () => void
    }

    export interface Popup {
        show: (props: Config) => void
        hide: () => void
    }

    export interface SPSheet {
        show: (props: SheetConfig) => void
        setHeight: (height: number, onOpenComplete: () => void) => void
        hide: () => void
    }

    export const Toast: Toast
    export const Popup: Popup
    export const SPSheet: SPSheet
    export const Root: FC
    export const getStatusBarHeight: FC
    export const isIPhoneWithMonobrow: FC
}
```

**Comment by Kevinrp22** [comment]
Thank you for the quick response!

I can confirm that it solves the issue, but only for the examples I provided.

To give another example, 'bodyComponent' is not typed.

These are just examples, and there’s no rush. It would be worth checking the attributes in the documentation against the declared types to ensure they all match exactly.

Thanks! :)

**Comment by sekizlipenguen** [comment]
Hi there! 🎉
We’ve expanded and improved the type definitions based on your request. You can check out the changes in this commit:
[85918f9 - TypeScript type definitions updated](https://github.com/sekizlipenguen/react-native-popup-confirm-toast/commit/85918f9750020d17c6e7b7ee03164fdc765b5eb7)

When you have a chance, we’d love for you to review the updates. If you encounter any errors or notice something missing in the type definitions, please let us know. Thanks in advance for your feedback! 😊

**Comment by Kevinrp22** [comment]
Hi, thank you so much! I’ve reviewed it, and most of the missing ones are there, but these are still missing specifically:

### PopupConfig:
**`bodyComponentForce`
`onLayout`
`background`**

Could you publish these changes to npm?

Thank you! 😊

**Comment by sekizlipenguen** [comment]
Hi,

We wanted to let you know that the reported issues, including [#27](https://github.com/sekizlipenguen/react-native-popup-confirm-toast/issues/27), have been addressed. The updates are now implemented.

Please check and confirm if everything works as expected.

@sekizlipenguen/react-native-popup-confirm-toast@1.0.1

Thanks for your feedback! 😊

**Comment by Kevinrp22** [comment]
Helllo!,

I installed the new package and when I updated the import path, I get an error:

**`"@sekizlipenguen/react-native-popup-confirm-toast/index.d.ts" is not a module`**

![image](https://github.com/user-attachments/assets/f2bd2401-bfb3-40a1-8eb5-54ece0dd6c94)

**Comment by sekizlipenguen** [comment]
Hi @Kevinrp22,

Could you please try updating the index.d.ts file as shown below and test it?

```
declare module "react-native-popup-confirm-toast" {
    import {FC, ReactNode} from "react";
    import {LayoutChangeEvent, StyleProp, TextStyle, ViewStyle} from "react-native";

    // Toast Config
    export interface ToastConfig {
        title?: string;
        text?: string;
        titleTextStyle?: StyleProp<TextStyle>;
        descTextStyle?: StyleProp<TextStyle>;
        backgroundColor?: string;
        timeColor?: string;
        position?: "top" | "bottom";
        icon?: FC | ReactNode;
        timing?: number;
        statusBarType?: "default" | "dark-content" | "light-content";
        statusBarTranslucent?: boolean;
        statusBarHidden?: boolean;
        statusBarAndroidHidden?: boolean;
        statusBarAppleHidden?: boolean;
        hiddenDuration?: number;
        startDuration?: number;
        onOpen?: () => void;
        onOpenComplete?: () => void;
        onClose?: () => void;
        onCloseComplete?: () => void;
    }

    // Popup Config
    export interface PopupConfig {
        title?: string;
        textBody?: string;
        type?: "success" | "info" | "danger" | "warning" | "confirm";
        buttonText?: string;
        confirmText?: string;
        cancelCallback?: () => void;
        callback?: () => void;
        icon?: FC | ReactNode;
        iconHeaderStyle?: StyleProp<ViewStyle>;
        containerStyle?: StyleProp<ViewStyle>;
        modalContainerStyle?: StyleProp<ViewStyle>;
        background?: string;
        bodyComponent?: FC<{ popupProps: any; onLayout?: (event: LayoutChangeEvent) => void }>;
        bodyComponentForce?: boolean;
        timing?: number;
        onOpen?: () => void;
        onOpenComplete?: () => void;
        onClose?: () => void;
        onCloseComplete?: () => void;
    }

    // Sheet Config
    export interface SheetConfig {
        background?: string;
        height?: number;
        duration?: number;
        closeDuration?: number;
        closeOnDragDown?: boolean;
        closeOnPressMask?: boolean;
        closeOnPressBack?: boolean;
        dragTopOnly?: boolean;
        component?: FC<{ sheetProps: any }>;
        onOpen?: () => void;
        onOpenComplete?: () => void;
        onClose?: () => void;
        onCloseComplete?: () => void;
        customStyles?: {
            draggableIcon?: StyleProp<ViewStyle>;
            container?: StyleProp<ViewStyle>;
            draggableContainer?: StyleProp<ViewStyle>;
        };
        timing?: number;
        keyboardHeightAdjustment?: boolean;
    }

    export interface Toast {
        show: (config: ToastConfig) => void;
        hide: () => void;
    }

    export interface Popup {
        show: (config: PopupConfig) => void;
        hide: () => void;
    }

    export interface SPSheet {
        show: (config: SheetConfig) => void;
        hide: () => void;
        setHeight: (height: number, onComplete?: () => void) => void;
    }

    // Root Props Definition
    export interface RootProps {
        children?: ReactNode;
        style?: StyleProp<ViewStyle>;
    }

    export const Toast: Toast;
    export const Popup: Popup;
    export const SPSheet: SPSheet;
    export const Root: FC<RootProps>;
    export const getStatusBarHeight: () => number;
    export const isIPhoneWithMonobrow: () => boolean;
}

```

**Comment by Kevinrp22** [comment]
The error persists. The solution is to change this:

**`declare module "react-native-popup-confirm-toast"`**

to this

**`declare module "@sekizlipenguen/react-native-popup-confirm-toast"`**

Changing that, the error disappears!
